### PR TITLE
fix #280: update coco reference

### LINKED ISSUE #280: ‘COCO’ object has no attribute 'cat_img_map'
**Checklist**

1. ‘COCO’ object has no attribute 'cat_img_map'

**Describe the bug**
When I run `./tools/dist_train.sh configs/textrecog/seg/seg_r31_1by16_fpnocr_toy_dataset.py work_dirs/seg 1`,it reports this error.
image

**Reproduction**

1. `./tools/dist_train.sh configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015.py work_dirs/mask 1`

**Bug fix**
Substitute `from pycocotools.coco import COCO` for `from mmdet.datasets.api_wrappers import COCO` in mmocr.datasets.icdar_dataset.py.

### PR DESCRIPTION
**Pull request by gaotongxiao**
#280

### CODE REVIEW

**Comment by innerlee** [comment]
Can this be tested?

**Comment by gaotongxiao** [comment]
It seems `mmdet=2.11.0` doesn't have the api wrapper. We need to finish #282 and update the dependency before applying this patch.

**Comment by innerlee** [comment]
Any solution that work on mmdet=2.11.0?

**Comment by gaotongxiao** [comment]
> Any solution that work on mmdet=2.11.0?
> 
> Or, is #280 caused by higher mmdet version?

It's just because we're using API names not provided by official COCO (https://github.com/open-mmlab/mmdetection/issues/2913#issuecomment-639893148). I guess there's no good solution for now.

**Comment by innerlee** [comment]
So is this caused by the recent drop of mmpycocotools?

**Comment by gaotongxiao** [comment]
> So is this caused by the recent drop of mmpycocotools?

Not a problem for `mmpycocotools`. Following the official installation instruction will install the official `pycocotools` instead of `mmpycocotools`.

**Comment by innerlee** [comment]
Okay so there will be no way to make both mmpycocotools and pycocotools happy?

**Comment by gaotongxiao** [comment]
> Okay so there will be no way to make both mmpycocotools and pycocotools happy?

Seems not. But we're working on #282 now so hopefully this issue can be fixed soon.

**Comment by innerlee** [comment]
For maximum compatibility, I think you can inspect the existence of property `cat_img_map`, and if non-exist, then use the counterpart in pycocotools.

**Comment by gaotongxiao** [comment]
> For maximum compatibility, I think you can inspect the existence of property `cat_img_map`, and if non-exist, then use the counterpart in pycocotools.

The problem comes from `CocoDataset`, which is a base class from MMDet. MMDet 2.11.0 assumes that the COCO object inside this class has `cat_img_map`, but it's not a standard property provided by pycocotools. We can copy the COCO wrapper in `MMDet 2.13.0` to MMOCR for maximum compatibility, but the safest way is still to upgrade the dependency and reuse their wrapper in case of any future change in their code.
